-- ====================================================================
-- 🚀 부산대 교환학생 필터: Supabase 데이터베이스 & 보안 설정 SQL
-- --------------------------------------------------------------------
-- [적용 방법]
-- 1. https://supabase.com 로그인 후 무료 새 프로젝트 생성
-- 2. 왼쪽 메뉴의 [SQL Editor] 클릭 -> [New Query] 클릭
-- 3. 이 파일의 전체 내용을 복사하여 붙여넣고 [Run (Ctrl+Enter)] 실행
-- ====================================================================

-- 1. 검색 로그 테이블 생성
create table if not exists public.search_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    searcher_id text not null,
    filters jsonb default '{}'::jsonb,
    result_count integer default 0,
    result_names text[] default array[]::text[],
    user_agent text
);

-- 검색 속도 최적화를 위한 인덱스 생성
create index if not exists idx_search_logs_created_at on public.search_logs (created_at desc);
create index if not exists idx_search_logs_searcher_id on public.search_logs (searcher_id);

-- 2. Row Level Security(RLS, 행 수준 보안) 활성화
alter table public.search_logs enable row level security;

-- 누구나(익명 학생) 검색 로그를 등록(INSERT)할 수 있도록 허용하는 정책
drop policy if exists "Allow anonymous insert" on public.search_logs;
create policy "Allow anonymous insert"
on public.search_logs
for insert
to anon, authenticated
with check (true);


-- 3. 관리자 설정(비밀번호) 테이블 생성
create table if not exists public.admin_config (
    key text primary key,
    value text not null
);

-- 관리자 테이블 RLS 활성화 (일반 사용자는 절대 직접 조회/수정 불가)
alter table public.admin_config enable row level security;

-- 초기 기본 관리자 비밀번호: admin1234
insert into public.admin_config (key, value)
values ('admin_pass', 'admin1234')
on conflict (key) do nothing;


-- 4. 운영자 콘솔용 RPC 보안 함수 정의 (SECURITY DEFINER로 실행)

-- (1) 로그 조회 함수: 비밀번호 일치 시에만 전체 로그 반환
create or replace function public.admin_get_logs(pass text)
returns setof public.search_logs
language plpgsql
security definer
as $$
declare
    v_saved_pass text;
begin
    select value into v_saved_pass from public.admin_config where key = 'admin_pass';
    if v_saved_pass is distinct from pass then
        raise exception '비밀번호가 올바르지 않습니다.';
    end if;
    return query select * from public.search_logs order by created_at desc;
end;
$$;

-- (2) 특정 검색자의 기록 삭제 함수
create or replace function public.admin_delete_searcher(pass text, sid text)
returns void
language plpgsql
security definer
as $$
declare
    v_saved_pass text;
begin
    select value into v_saved_pass from public.admin_config where key = 'admin_pass';
    if v_saved_pass is distinct from pass then
        raise exception '비밀번호가 올바르지 않습니다.';
    end if;
    delete from public.search_logs where searcher_id = sid;
end;
$$;

-- (3) 전체 검색 기록 초기화 함수
create or replace function public.admin_clear_logs(pass text)
returns void
language plpgsql
security definer
as $$
declare
    v_saved_pass text;
begin
    select value into v_saved_pass from public.admin_config where key = 'admin_pass';
    if v_saved_pass is distinct from pass then
        raise exception '비밀번호가 올바르지 않습니다.';
    end if;
    truncate table public.search_logs;
end;
$$;

-- (4) 비밀번호 변경 함수
create or replace function public.admin_set_pass(pass text, new_pass text)
returns void
language plpgsql
security definer
as $$
declare
    v_saved_pass text;
begin
    select value into v_saved_pass from public.admin_config where key = 'admin_pass';
    if v_saved_pass is distinct from pass then
        raise exception '비밀번호가 올바르지 않습니다.';
    end if;
    update public.admin_config set value = new_pass where key = 'admin_pass';
end;
$$;

-- RPC 함수 실행 권한을 익명(anon) 및 인증 사용자에게 부여
grant execute on function public.admin_get_logs(text) to anon, authenticated;
grant execute on function public.admin_delete_searcher(text, text) to anon, authenticated;
grant execute on function public.admin_clear_logs(text) to anon, authenticated;
grant execute on function public.admin_set_pass(text, text) to anon, authenticated;
